return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = {
    "nvim-treesitter/nvim-treesitter-textobjects",
  },
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = {},
  },
  opts = {
    ensure_installed = {
      "asm",
      "bash",
      "c",
      "cmake",
      "comment",
      "cpp",
      "css",
      "csv",
      "dart",
      "diff",
      "dockerfile",
      "doxygen",
      "editorconfig",
      "elixir",
      "fish",
      "glsl",
      "go",
      "gomod",
      "html",
      "javascript",
      "json",
      "julia",
      "kdl",
      "latex",
      "linkerscript",
      "lua",
      "luadoc",
      "make",
      "markdown",
      "markdown_inline",
      "meson",
      "nim",
      "ninja",
      "nix",
      "pioasm",
      "python",
      "re2c",
      "regex",
      "ruby",
      "rust",
      "slint",
      "solidity",
      "sql",
      "svelte",
      "toml",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
      "zig",
    },
  },
}
